name: Deploy API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: 'https://ocurran21.github.io/NameThatPokemon/name-that-pokemon-backend/docs/swagger-ui/dist/'  # Ensure accurate URL reflecting your full path
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Verify Directory Structure
        run: |
          cd name-that-pokemon-backend/docs/swagger-ui/dist
          ls -l  # List files to ensure everything is in place
          touch .nojekyll  # Create .nojekyll in the target directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'name-that-pokemon-backend/docs/swagger-ui/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
